spring:
  freemarker:
    template-loader-path: classpath:/webapp/WEB-INF/ftl/
    cache: false
    check-template-location: true
    content-type: text/html; charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

