spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/luna_data_center?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
